src/Cxx/Visualization/CMakeLists.txt, src/Cxx/Visualization/PointDataSubdivision.cxx
Port the PointDataSubdivision.py Python example to C++.
=> ENH: Add PointDataSubdivision.cxx example.

src/Python/Visualization/OrientedGlyphs.py
This is a direct translation of `Cxx/Visualisation/OrientedGlyphs.cxx`.
I needed to do it for myself, and I figured I might as well share it.
=> add Python/Visualisation/OrientedGlyphs

src/Admin/VTKClassesUsedInExamples.py
Also removing extensions when making the classes used tables.
Thanks Bill
=> Removing the with statements so Py 2.7 will work.

src/Admin/VTKClassesUsedInExamples.py
=> Fixing file name error and reintroducing 'with'.

src/CSharp/IO/ReadPDB.cs, src/Cxx/IO/ReadPDB.cxx, src/Cxx/PolyData/ContoursToSurface.cxx, src/Cxx/Visualization/LabeledMesh.cxx
=> remove immediateModeRendering setting

src/Cxx/CompositeData/CompositePolyDataMapper.cxx, src/Cxx/Filtering/ImplicitBooleanDemo.cxx, src/Cxx/GeometricObjects/EllipticalCylinder.cxx, src/Cxx/GeometricObjects/EllipticalCylinderDemo.cxx, src/Cxx/GeometricObjects/TessellatedBoxSource.cxx, src/Cxx/IO/ReadAllPolyDataTypesDemo.cxx, src/Cxx/IO/VRMLImporterDemo.cxx, src/Cxx/Images/ResizeImageDemo.cxx, src/Cxx/ImplicitFunctions/ImplicitDataSet.cxx, src/Cxx/Points/ExtractClusters.cxx, src/Cxx/Texture/TextureCutQuadric.cxx, src/Cxx/Texture/TextureCutSphere.cxx, src/Cxx/Utilities/SaveSceneToFieldData.cxx, src/Cxx/Utilities/SaveSceneToFile.cxx, src/Cxx/Utilities/ShareCamera.cxx, src/Cxx/Utilities/ViewportBorders.cxx, src/Cxx/Visualization/AssignCellColorsFromLUT.cxx, src/Cxx/Visualization/CameraModel1.cxx, src/Cxx/Visualization/CameraModel2.cxx, src/Cxx/Visualization/ChooseTextColorDemo.cxx, src/Cxx/Visualization/ComplexV.cxx, src/Cxx/Visualization/LabeledMesh.cxx, src/Cxx/Visualization/PointDataSubdivision.cxx, src/Cxx/Widgets/AngleWidget2D.cxx, src/Cxx/Widgets/ContourWidget.cxx, src/Cxx/Widgets/SeedWidgetImage.cxx
=> fix more warnings exposedby buildbots

src/Cxx/CompositeData/HierarchicalBoxPipeline.cxx, src/Cxx/DataStructures/KDTreeTimingDemo.cxx, src/Cxx/DataStructures/ModifiedBSPTreeTimingDemo.cxx, src/Cxx/DataStructures/OBBTreeTimingDemo.cxx, src/Cxx/DataStructures/OctreeTimingDemo.cxx, src/Cxx/Developers/FilterSelfProgress.cxx, src/Cxx/Developers/ImageAlgorithmFilter.cxx, src/Cxx/Developers/MultipleInputPorts.cxx, src/Cxx/Developers/vtkTest.cxx, src/Cxx/Developers/vtkTest.h, src/Cxx/Developers/vtkTestFilterSelfProgressFilter.cxx, src/Cxx/RenderMan/PolyDataRIB.cxx, src/Cxx/Visualization/CurvatureBandsWithGlyphs.cxx
=> added more warning fixes

src/Cxx/Widgets/TextWidget.cxx
Remove `vtkTextActor` duplicate include.
=> ENH: Remove duplicate vtkTextActor include.

src/Cxx/Qt/BorderWidgetQt.cxx, src/Cxx/Qt/EventQtSlotConnect.cxx
This fixes: the C2593   'operator =' is ambiguous errors.
=> Fix ambiguous assignment error.

src/Cxx.md, src/Cxx/VisualizationAlgorithms/BluntStreamlines.cxx
I have also added a hint for the test file names.
=> BluntStreamlines was missing in Cxx.md

src/Cxx.md, src/Cxx/Rendering/Rotations.cxx, src/Python.md, src/Python/Rendering/Rotations.py
Added Rotations.py and some minor changes to Rotations.cxx.
A Rotations entry was also added to Cxx.md and Python.md.
Essentially the changes to Rotations.cxx were:
1) Remove extra iren->Start(); statements as these were causing crashes in Windows.
2) Add in code that can be used to replicate the cow colour and background as in VTKTextbook.pdf.
3) Add in an option to specify what rotation is to be displayed.
4) Reformat the file using clang-format.
=> Adding Rotations.py

src/Cxx/Rendering/WalkCow.cxx, src/Python/Rendering/WalkCow.py
Fixed some minor things in WalkCow.cxx
Added display options for WalkCow.py.
=> Adding options for display.

src/Admin/ScrapeRepo
@lorensen Please check carefully!
Also print statements now work in Python 3.x
=> Add Python Snippets to ScrapeRepo.

CMake/WikiModuleConfig.cmake, module.cmake
=> COMP: Generalize handling of optional VTK dependencies 

src/Cxx/Rendering/Rotations.cxx, src/Cxx/Rendering/WalkCow.cxx, src/Cxx/Visualization/Hawaii.cxx, src/Cxx/VisualizationAlgorithms/DisplacementPlot.cxx, src/Cxx/VisualizationAlgorithms/PlateVibration.cxx, src/Cxx/VisualizationAlgorithms/StreamlinesWithLineWidget.cxx, src/Cxx/VisualizationAlgorithms/VelocityProfile.cxx, src/Python/Rendering/WalkCow.py, src/Python/Visualization/Hawaii.py, src/Python/VisualizationAlgorithms/DisplacementPlot.py
1. A better lambda function for setting user defined colors. Renamed from **Scale** to **SetColor**.
2. Use `std::array` instead of `std::vector` for setting colors. This means we can apply a transform and then just use the `.data()` of the std::array when setting the color.
2. For optional parameters, checking limits where needed.
1. For optional parameters, checking limits where needed.
=> Making better code.

src/Python.md
This is a better link as it covers both Windows and Linux. I wrote this a long time ago.
Utkarsh has now also updated it to incorporate the changes that have happened in VTK 9.0.
See: [Python environment fixes](https://gitlab.kitware.com/vtk/vtk/merge_requests/3596) for what the changes were.
=> Updating the environment instructions for Python.

src/Python/Visualization/NamedColors.py
Fixed an error relating to raise and simplified the code.
Also commented out the needless writing of the image.
=> Fix named colors

src/Cxx/Rendering/WalkCowA.cxx, src/Cxx/Rendering/WalkCowB.cxx, src/Python/VisualizationAlgorithms/AnatomicalOrientation.md
Also update the AnatomicalOrientation markdown file in the Python folder.
=> Fix include headers so current directory is searched first.

src/Python/VisualizationAlgorithms/OfficeA.py, src/Python/VisualizationAlgorithms/PineRootConnectivityA.py
=> Copy paste error for PineRootConnectivityA.py

src/Admin/ValidateMarkdown.py, src/Python.md
The only files that can be validated are:
- CSharp.md, Cxx.md, Java.md, Python.md, VTKBookFigures.md
=> Updating ValidateMarkdown.py to also check the links.

src/Admin/FindMissingExamples.py
Easier to understand, much better layout, and ... excluding folders works now.
Python now has no missing examples.
=> A major rewrite of FindMissingExamples.

src/Cxx/Visualization/Hanoi.cxx, src/Cxx/Visualization/LabeledMesh.cxx
When building statically, the order of destruction is undefined and if
the order is not done correctly, `vtkDebugLeaks` ends up crashing.
---
Cc: @bradking
=> static data: do not place VTK objects in static data

src/VTKFileFormats.md
I tested this using `mkdocs serve` and it seems to work, giving a really nice layout.
=> Using HTML in the markdown to get nice looking text.

src/VTKFileFormats.md
Did a bit of careful reading. Also added in a link to Figure 1.
Figure 4 looks really nice, I also like the link to the source code.
=> Fix minor editorial issues in VTKFileFormats.md.

src/VTKFileFormats.md
Moved to CSS styling and indented the tables a little.
=> Fixing Figure 1

src/Cxx/GeometricObjects/IsoparametricCellsDemo.cxx, src/Cxx/GeometricObjects/LinearCellDemo.cxx, src/Cxx/GeometricObjects/PolyLine1.cxx
Visual Studio picked up the missing return, not gcc.
=> Missing return statement. Also added a space before namespace.

src/Python/Graphs/NOVCAGraph.py
SetInput is deprecated and not available in VTK 8.1.
=> Update NOVACAGraph.py to use SetInputData

src/VTKBookLaTex/Chapter03.tex
=> Fix equation.

src/VTKBookLaTeX/VTKTextBook.tex
List of Figures, Tables, Equations and Listings are now listed in the Table of Contents.
=> Adding the lists to the tables of contents.

src/Cxx.md, src/Python.md, src/Python/Utilities/SaveSceneToFieldData.md, src/Python/Utilities/SaveSceneToFieldData.py, src/Python/Utilities/SaveSceneToFile.md, src/Python/Utilities/SaveSceneToFile.py
@lorensen Just added the Save Scene examples.
=> Adding SaveScene python examples.

src/Cxx/IO/ReadLegacyUnstructuredGrid.cxx
@martinken @lorensen this now matches the original image.
I'll do the merge as it is a minor change.
=> Rework ReadLegacyUnstructuredGrid to match original image.

src/Java/DataStructures/VisualizeKDTree.java, src/Java/Graphs/SelectGraphVertices.java, src/Java/IO/ReadPolyData.java, src/Java/IO/WritePolyData.java, src/Java/Imaging/ImageTest.java, src/Java/ImplicitFunctions/ImplicitSphere.java, src/Java/Miscellaneous/Cone6.java, src/Java/Miscellaneous/Cutter.java, src/Java/Miscellaneous/Screenshot.java, src/Java/SwingIntegration/SwingHandleMouseEvent.java, src/Java/Visualization/AnimDataCone.java, src/Java/Visualization/ColorAnActor.java, src/Java/Visualization/Follower.java, src/Java/Visualization/VectorFieldExample.java
The native libraries were not loading when the example programs were tried in eclipse. I have modified the procedure for loading, in almost all the examples.
=> Updating procedure for load native libraries

src/Cxx.md, src/Cxx/Visualization/OpenVRCone.md, src/Cxx/Visualization/OpenVRCube.md, src/Cxx/Visualization/OpenVRCylinder.md, src/Cxx/Visualization/OpenVRSphere.md
Also fixed the markdown descriptions.
=> OpenVR was not integrated into the web site.

src/Admin/VTKClassesUsedInExamples.py
Fixes:
1) Not all vtk classes were being obtained from the VTK web site, e.g. vtkPolyDataMapper. Now 2729 classes are found instead of 2369.
2) Excluded some more classes.
2) The excluded classes is now a table.
=> Enhancing classes used script

src/Java/Filtering/Glyph2D.md, src/Java/Utilities/TimerLog.md, src/Java/Visualization/Cursor2D.md
@chakravarthi589 Please note the fixes I had to do to the markdown files.
=> Fixing the recent markdown files

src/Java.md, src/Java/Video/OggTheora.java, src/Java/Video/OggTheora.md
=> Add ogg theora

src/Cxx/Qt/BorderWidgetQt.cxx, src/Cxx/Qt/BorderWidgetQt.ui, src/Cxx/Qt/BorderWidgetQtDriver.cxx, src/Cxx/Qt/EventQtSlotConnect.cxx, src/Cxx/Qt/ImageDataToQImage.cxx, src/Cxx/Qt/QImageToImageSource.cxx, src/Cxx/Qt/QtBarChart.cxx, src/Cxx/Qt/RenderWindowNoUiFile.cxx, src/Cxx/Qt/RenderWindowUIMultipleInheritance.cxx, src/Cxx/Qt/RenderWindowUIMultipleInheritanceDriver.cxx, src/Cxx/Qt/RenderWindowUISingleInheritance.cxx, src/Cxx/Qt/ShareCameraQt.cxx, src/Cxx/Qt/ShareCameraQt.ui, src/Cxx/Qt/ShareCameraQtDriver.cxx, src/Cxx/Qt/SideBySideRenderWindowsQt.cxx, src/Cxx/Qt/SideBySideRenderWindowsQt.ui, src/Cxx/Qt/SideBySideRenderWindowsQtDriver.cxx
- Adding some color to the Qt examples, making them look nice!
- Replacing the deprecated class `QVTKOpenGLWidget` with `QVTKOpenGLNativeWidget`.
=> Updating the Qt examples

src/Cxx/Rendering/InterpolateCamera.cxx
1) Added `#include <iterator>` this is needed by gcc 8.2
2) Merged the anonymous namespaces.
=> Failed to compile with gcc 8.2

src/Java.md, src/Java/DataStructures/BuildOctree.java, src/Java/DataStructures/BuildOctree.md
=> Add build octree

src/Cxx/Geovis/CMakeLists.txt, src/Cxx/PolyData/ExternalContour.cxx, src/Cxx/PolyData/PointInsideObject.cxx, src/Cxx/Utilities/Screenshot.cxx, src/Cxx/Utilities/ZBuffer.cxx, src/Cxx/Visualization/Hanoi.cxx
@lorensen This should be Ok for older versions. A whole lot of deprecated functions were removed in a VTK commit today.
=> VTK 8.90 has removed these deprecated functions/classes

src/Cxx/GeometricObjects/ParametricObjectsDemo.cxx, src/Cxx/Snippets/WriteImage.md
The command line parser is now a class.
Minor changes to WriteImage.
=> Adding better error checking

src/Cxx/GeometricObjects/ParametricObjectsDemo.cxx, src/Python/GeometricObjects/ParametricObjectsDemo.py
=> Normals can only be computed for polygons and triangle strips.

src/Cxx/IO/ImportPolyDataScene.cxx
In light of Allie's newly added feature(VTK [MR!5158](https://gitlab.kitware.com/vtk/vtk/merge_requests/5158)) of for-range support for
vtkCompositeDataSets, this commit updates the ImportPolyDataScene
example.
=> Add a for-range usage example for vtkCompositeDataSet

VTKNamedColorPatches.html, src/Cxx/Visualization/NamedColorPatches.cxx, src/Cxx/Visualization/NamedColorPatches.md, src/Python/Visualization/NamedColorPatches.md, src/Python/Visualization/NamedColorPatches.py
Among the changes are:
1. The C++ and Python code has been modernised and re-organised.
2. Identical HTML output is produced using either the C++ or Python code.
3. The HTML output has been "beautified".
4. Internal CSS is used to define a style  in the head section of the HTML page.
5. The HTML code has been validated using the [W3C Markup Validation Service](https://validator.w3.org/).
=> A major rewrite/update of NamedColorPatches

src/Cxx/GeometricObjects/CellTypeSource.cxx, src/Cxx/GeometricObjects/ParametricObjectsDemo.cxx, src/Cxx/IO/ImportPolyDataScene.cxx
Also `src/Cxx/IO/ImportPolyDataScene.cxx`
=> Running CppCheck and modernising any of the changed GeometricObjects files

src/Cxx/IO/3DSImporter.cxx, src/Cxx/IO/ExportPolyDataScene.cxx, src/Cxx/IO/FindAllArrayNames.cxx, src/Cxx/IO/ImageWriter.cxx, src/Cxx/IO/ImportPolyDataScene.cxx, src/Cxx/IO/OBJImporter.cxx, src/Cxx/IO/VRMLImporter.cxx, src/Cxx/IO/VRMLImporterDemo.cxx, src/Cxx/Snippets/WriteImage.md
Also `src/Cxx/Snippets/WriteImage.md`
=> Running CppCheck and modernising any of the changed IO files

src/Cxx/Points/CompareExtractSurface.cxx, src/Cxx/Points/ExtractPointsDemo.cxx, src/Cxx/Points/MaskPointsFilter.cxx, src/Cxx/Points/SignedDistance.cxx, src/Cxx/Points/UnsignedDistance.cxx
Unable to test CompareExtractSurface.cxx but "should"be Ok.
=> Running CppCheck and modernising any of the changed Points files

src/Cxx/GeometricObjects/Cell3DDemonstration.cxx, src/Cxx/GeometricObjects/Polyhedron.cxx, src/Cxx/PolyData/ExtractPolyLinesFromPolyData.cxx, src/Cxx/PolyData/FitSplineToCutterOutput.cxx, src/Cxx/Utilities/ShepardMethod.cxx, src/Cxx/Visualization/BackgroundTexture.cxx, src/Cxx/Visualization/LabelContours.cxx, src/Cxx/VisualizationAlgorithms/TubesWithVaryingRadiusAndColors.cxx
This patch prepares the repo for incoming changes to the `vtkCellArray` API.
=> Update to reflect vtkCellArray API changes.

src/Python.md, src/Python/PolyData/IterateOverLines.py
=> Add source code for IterateOverLines
