src/Python/Visualization/ElevationBandsWithGlyphs.py

Fix typo in ElevationBandsWithGlyphs.py example function name: change
"WritePMG" to "WritePNG".

STYLE: Fix typo in ElevationBandsWithGlyphs.py function name,

---

src/Instructions/ForDevelopers.md

Fix typo in the "Review changes in a browser" section: change "nstalled"
to "installed".

DOC: Fix typo in Developer instructions page.

---

src/Instructions/Guidelines.md

Fix bracket style of a program's main function signature example: change
"char *argv{}" to "char *argv[]".

DOC: Fix typos in Instructions/Guidelines.md file.

---

src/Cxx/Filtering/Glyph3D.cxx

Remove unused and unnecessary variable from the vtkGlylph3D.cxx example.

ENH: Remove unused variable from vtkGlyph3D.cxx.

---

src/Admin/VTKClassesUsedInExamples.py

Produce tables of VTK classes and their corresponding usage in the examples.
There is also  an option to produce a list of unused classes in the examples.
The markdown tables are written to the src directory in the VTK Example source file directory.
Typical usage:
- Produce tables of classes used in some_path/VTKExamples/src:
`VTKClassesUsedInExamples.py some_path/VTKExamples/src`
- Produce tables of classes used and those not used in some_path/VTKExamples/src:
`VTKClassesUsedInExamples.py some_path/VTKExamples/src -u`
To add links to the VTK class documentation on the web, just add **-a** as a parameter.
To vary the number of columns for unused classes to say 8, just add **-c8** as a parameter.

Produce tables of VTK classes used in the examples.

---

src/Cxx/CompositeData/CompositePolyDataMapper.cxx

Block-attributes are mapped by vtkDataObject*.

Using the new API of vtkCompositeDataDisplayAttributes.

---

src/Cxx/CompositeData/CompositePolyDataMapper.cxx

vtkCompositeDataDisplayAttributes now maps block attributes by vtkDataObject*.

Using CompositeMapper2's API to set block attributes.

---

src/Cxx/Rendering/WalkCow.cxx

Without it, VTK_MAJOR_VERSION and VTK_MINOR_VERSION macros were not
defined, leading to compile failures in VTK 8.1.

vtkVersionMacros.h needed to be included

---

src/Cxx/Qt/CMakeLists.txt

This commit fixes the following error:
```
[...]
-- Found Qt4: /home/jcfr/Support/qt-everywhere-opensource-build-4.8.7/bin/qmake (found version "4.8.7")
CMake Error at src/Cxx/Qt/CMakeLists.txt:64 (TARGET_LINK_LIBRARIES):
Cannot specify link libraries for target "BorderWidgetQt" which is not
built by this project.
[...]

COMP: Fix configure error when build against Qt4

---

CMakeLists.txt

The version now match the one used in VTK 8.1.
Note that this doesn't prevent us from building against VTK6 or VTK7.

ENH: Update minimum required version of CMake from 2.8.8 to 3.3

---

CMake/WikiModuleConfig.cmake
CMake/WikiModuleConfigLegacy.cmake
CMakeLists.txt

Hi Bill,
This PR fixes the build broken when using VTK >= kitware/VTK@061eff0, it basically improves and simplifies the build system to use `vtkExternalModuleMacros`.
For more details, see https://gitlab.kitware.com/vtk/vtk/merge_requests/3451
<hr>
```
BUG: Fix VTK build using vtkExternalModuleMacros
This commit fixes the configuration and build of VTKWikiExamples as both a
VTK remote module and a stand-alone project. It ensure **first and follow-up
configurations** produce similar results and behave **identically**.
The build was broken following the introduction of
Kitware/VTK@e33b90d (ExternalModule: Improve target export to
allow build against external module).
The commit addresses the issue by introducing the WikiModuleConfig CMake
module responsible for:
* ensure module information …
```

BUG: Fix VTK build using vtkExternalModuleMacros

---

src/Cxx/Visualization/Blow.cxx
src/Python/Visualization/Blow.py

I translated the c++ code from Python and accidentally left in an **and**.  My gcc compiler accepted it however Visual Studio didn't. Apparently according to this: [Logical operators](http://en.cppreference.com/w/cpp/language/operator_logical) "and", "or" and "not" can be used. This is why the gcc compiler accepted it. The things you learn!
It always pays to try different compilers!

Fix logic.

---

src/Python.md

This should make it easier for users of the site and the indexing will be almost identical for Cxx and Python.
I have reorganised and also moved some of the links about to more closely match `Cxx.md`.
Additionally I have added/removed headings to match `Cxx.md`.
Personally I think it will be easier to follow the same layout in Python as Cxx. I found it a bit confusing when the same named program appeared under a different heading. E.g. in the case of **Display** in Python, a lot of the programs moved to **Cells** and **Sources** to match the Cxx layout.
I validated by running `FindMissingExamples.py` and reformatting with `ValidateMarkdown.py` so I am confident everything is there.

Reorganising Python.md so that headings match Cxx.md

---

src/VTKBookLaTex/ReadMe.md

Reference the [Bibliography](https://github.com/lorensen/VTKExamples/blob/master/src/VTKBookLaTex/Bibliography.bib)
file correctly: `Bibliography.bib` instead of `Bibliography.tex`.
Link it to the actual file.

DOC: Reference the bibliography file correctly.

---

src/VTKBookLaTex/VTKTextBook.tex

Also \loadglsentries{Glossary} must come before \makeglossaries.

Now using roman numerals for introductory page numbers.

---

src/Cxx/Geovis/CMakeLists.txt

The issue was that CMake's `file(GLOB..)` returns full paths to all
files. Instead of truncating the path later on, this change tells the
GLOB operator to return the file paths relative to the current source
directory. This ensures that the deprecated files get removed by name
only.
Also, fixed a typo in the GeoGraticle.

BUG: Deprecated classes were still being compiled with VTK_LEGACY_REMOVE

---

src/VTKBookLaTex/MakeDocument.bash
src/VTKBookLaTex/MakeDocument.cmd
src/VTKBookLaTex/Title.tex

In Linux the glossary was not being indexed. This fix fixes that.

Fixing the build script.

---

src/VTKBookLaTeX/VTKTextBook.md

The source files have been moved to to the VTK repository [textbook](https://gitlab.kitware.com/vtk/textbook#). For the interim (and as a backup) source files will still remain here.
@lorensen, I have added a note to this effect.

Moved VTKBookLaTeX to the VTK textbook repository.

---

src/Cxx/Developers/vtkTestFilterProgressFilter.h
src/Cxx/Developers/vtkTestFilterSelfProgressFilter.h
src/Cxx/Developers/vtkTestMultipleInputPortsFilter.h
src/Cxx/Developers/vtkTestProgressReportFilter.h

We now use the C++11 equivalents override and delete.

VTK_OVERRIDE and VTK_DELETE_FUNCTION are deprecated

---

src/Admin/VTKClassesUsedInExamples.py

If `tmp` is a list `tmp.clear()` does not work for Python < 3.3, use `del tmp[:]` instead.

Fixing a Python 2.7 issue

---

CMakeLists.txt
src/Cxx/Qt/CMakeLists.txt

@lorensen These changes allow Qt to build with VTK 8.90 and VTK 8.0. I have tested on VTK 8.90, VTK 8.2 with Qt 5.12. Please note that I have removed the Qt4 references/logic so these files are consistent with the web template.
I hope this doesn't  break what you are doing wrt the remote modules!

Update CMakeLists.txt files to enable Qt builds

---

src/Cxx/Meshes/CapClip.cxx
src/Cxx/Snippets/ReadPolyData.md
src/Python/Meshes/CapClip.py

In ReadPolyData removed the dependency on kwsys and the function signature is now:
```c++
vtkSmartPointer<vtkPolyData> ReadPolyData(std::string const& fileName)
```

Updating ReadPolyData, CapClip: fixing window names, minor changes

---

src/Cxx/Rendering/Shadows.cxx
src/Python/Rendering/Shadows.py

SetViewUp method already orthogonalizes ViewUp vector by calling ComputeViewTransform(), which calls Transform->SetupCamera().
OrthogonalizeViewUp() is not called after SetViewUp in any other examples or tests.

Remove redundant OrthogonalizeViewUp calls

---

src/Cxx/Untested/HasBugs/vtkglut.cxx

__APPLE_CC__ is an obsolete macro for clang version. Instead, conditionalize by platform, not compiler. Hoisted the same snippit from VTK itself.

Remove use of __APPLE_CC__

---

src/Cxx/Rendering/PhysicallyBasedRendering.cxx
src/Cxx/Rendering/Skybox_PBR.cxx
src/Python/Rendering/PhysicallyBasedRendering.py
src/Python/Rendering/Skybox_PBR.py

In in VTK 90+, vtkRenderer->SetEnvironmentCubeMap() has been replaced by vtkRenderer->SetEnvironmentTexture()

VTK 90 replace SetEnvironmentCubeMap()

---

src/VTKBook/04Chapter4.md

Remove the spare white space in the Wernecke94 reference used in `Chapter
4` `The Visualization Pipeline`, section `4.7 Programming Models`:
https://lorensen.github.io/VTKExamples/site/VTKBook/04Chapter4/#412-references

BUG: Remove the spare white space in Chapter 4 Wernecke94 reference
